version: '3.8'
services:
  php-apache-environment:
    container_name: cinema-booking
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./php/src:/var/www/html/
    ports:
      - 8100:80
  db:
    container_name: mysql-db
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: cinema
      MYSQL_USER: rwuser
      MYSQL_PASSWORD: rwuserpwd
    ports:
      - 3306:3306
